version: '2'
services:
  app:
    container_name: wordpress_app
    build: ./docker/app
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./logs:/var/log
     - ./logs/nginx:/var/log/nginx
     - ./wordpress:/var/www/html
    networks:
     - appnet
  db:
    container_name: wordpress_db
    image: percona:5.7
    ports:
     - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
     - ./database:/var/lib/mysql
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
