#!/usr/bin/env bash

cd build/wordpress
docker build -t jasonraimondi/wordpress:$1 -t jasonraimondi/wordpress:latest .
docker push jasonraimondi/wordpress:$1
docker push jasonraimondi/wordpress:latest
